### ISSUE TITLE
Use MathJax instead of LaTeX

### ISSUE THREAD

**Issue by tadamcz** [benthamite/EA-numbers#2]
> [MathJax](https://www.mathjax.org/) is a modern, browser-based typesetting system, useful for mathematical and chemical equations. It does not require the installation of any extra software, so it is easy to use, and it is recommended for most users.

[https://docs.ankiweb.net/math.html](https://docs.ankiweb.net/math.html)

I don't know how much effort it would be to re-write the math in MathJax.

**Comment by y-arjun-y** [comment]
Using <kbd>Cmd</kbd> + <kbd>fn</kbd> + <kbd>F2</kbd> in VS Code made this much easier!

**Comment by benthamite** [comment]
The original deck already uses MathJax: you can see this by inspecting the [Ankiweb-hosted version](https://ankiweb.net/shared/info/1810848608). For some mysterious reason, however, the MathJax was converted to LaTeX when the deck was exported as a json file. I just tried re-exporting it and the MathJax was preserved, so I have no clue about what happened. Perhaps earlier versions of the CrowdAnki plugin did not support MathJax? In any case, this is now solved.

**Comment by tadamcz** [comment]
After updating with CrowdAnki, I can confirm the maths now displays as expected in Anki for MacOS and iOS. Thank you!
